version: '3.4'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db
  #     - redis
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     RAILS_ENV: development
  #     DB_USERNAME: root
  #     DB_PASSWORD: root
  #     DB_DATABASE: sample
  #     DB_PORT: 3306
  #     DB_HOST: db
  #     RAILS_ENV: production
  #     RAILS_MAX_THREADS: 5
  #     REDIS_HOST: redis
  app:
    build:
      # command: bundle exec rails s -p 3000 -e development -b '0.0.0.0'
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: sample
      DB_DATABASE: sample
      DB_PORT: 3306
      DB_HOST: db
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # BUNDLE_PATH: /bundle
    volumes:
      - ../:/rails-app
      # - bundle:/bundle
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    expose:
      - '3000'

  db:
    image: 'mysql:5.7'
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
        - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/run/mysqld
    logging:
      driver: none
    ports:
      - '33061:3306'
  redis:
    image: redis:5.0.7

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
      - db
      - redis
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
      REDIS_HOST: redis

    entrypoint: sh ./entrypoints/sidekiq-entrypoint.sh

    links:
      - app
      - db

    # network_mode: 'host'

volumes:
  # bundle:
  db:
  gem_cache:
  node_modules:

    # Use a custom driver
    # driver: overlay2
